GET http://localhost:5000/hello

###

PUT http://localhost:5000/hello
content-type: application/json

{
  "msg": "hello"
}

###
GET http://localhost:5000/test/jsonsearchquery

###
GET http://localhost:5000/test/jsonautosuggest?q=hello&max=5